### ISSUE TITLE
Add paid videos

### ISSUE THREAD

**Issue by Benjioe** [Ldoppea/first-steps-dev#18]
[Plurasight](https://www.pluralsight.com) have great videos, but you have to pay for them. Can I add some them on first-steps-dev

**Comment by Ldoppea** [comment]
Hi,

As stated in our [contribution rules](https://first-steps.dev/#/./CONTRIBUTING), we prefer to focus on free links.

The goal of this list is more about "discovering" a field than "mastering" it. 
So users who read those links can understand the minimum viable to make a choice about using the techno or methodology or not using it. 
Having to pay to discover something that you don't even know if you need it, is a real barrier for its adoption. The paid options should come after the "first steps".

I hope you will understand our point of view :flushed:

**Comment by Benjioe** [comment]
Ok, I understand, but because they have a free trial plan and there is not many links for now, I had to ask.

Personal note: Next time, read the contribution guide before contributing... 😳
