### ISSUE TITLE
Remove english content from FR docs

### ISSUE THREAD

**Issue by sinedied** [Ldoppea/first-steps-dev#23]
Now that we have a dedicated english page, it may be time to remove all EN content from the FR page, what do you think?

**Comment by Ldoppea** [comment]
Yep, if they are in the English section we can delete them, and also we should delete the instructions about flags in the French page and the `CONTRIBUTING` section.

Maybe we should also add a section that say something like "you can find resources in your language by using the top right menu, if not there you can help us by adding your language with a PR".
